version: '3.8'

services:
  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: analytics-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - fraud-net

networks:
  fraud-net:
    external: true
    name: devops_fraud-net